# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'interactiveClassroom' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for interactiveClassroom
  pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
  pod 'OpenTok', '~> 2.9.0'

  target 'interactiveClassroomTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

[
  'Firebase',
  'Firebase/Core',
  'Firebase/Auth',
  'Firebase/Storage',
  'Firebase/Database',
  'Firebase/RemoteConfig',
  'Firebase/Messaging'
].each do |lib|
  pod lib
end

